### ISSUE TITLE
[Solved]output error

### ISSUE THREAD

**Issue by koolerkx** [wlerin/showroom#22]
Hello, I am new to use this program.
I cannot use this program as it shows there is a SyntaxError.

output:

```
ktx@ktx:/media/ktx/USB/showroom-master$ python showroom.py --help
Traceback (most recent call last):
  File "showroom.py", line 2, in <module>
    from showroom.main import main
  File "/media/ktx/USB/showroom-master/showroom/main.py", line 1, in <module>
    from showroom.interfaces import BasicCLI
  File "/media/ktx/USB/showroom-master/showroom/interfaces.py", line 111
    print(*output, sep='\n')
          ^
SyntaxError: invalid syntax
```

also

```
ktx@ktx:/media/ktx/USB/showroom-master$ python showroom.py --all
Traceback (most recent call last):
  File "showroom.py", line 2, in <module>
    from showroom.main import main
  File "/media/ktx/USB/showroom-master/showroom/main.py", line 1, in <module>
    from showroom.interfaces import BasicCLI
  File "/media/ktx/USB/showroom-master/showroom/interfaces.py", line 111
    print(*output, sep='\n')
          ^
SyntaxError: invalid syntax
```

Am I setting something wrong? Or not install completely?
I am using Ubuntu 19.04, Python 3.7.3

Hope someone could help me.

**Comment by wlerin** [comment]
Are you sure you're using 3.7.3? What's the output of `python -V` ? 

Does it work if you use `python3 showroom.py` instead?

That error is symptomatic of Python 2.

**Comment by koolerkx** [comment]
Ops, I am sorry, it's my mistake, I found that my python version is wrong.
The default python command is python2.7.16.
`python3 showroo.py` is work.

Thank you.
